version: "3"

services:
  db-postgres-wisewallet:
    image: postgres:alpine
    ports:
      - "5430:5432"
    container_name: "db-postgres-editaisupe"
    restart: always
    volumes:
      - ./bd-postgres-editaisupe:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
volumes:
  db-postgres-editaisupe:
